# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filestream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filestream.proto',
  package='filestream',
  syntax='proto3',
  serialized_options=b'\252\002\nFileStream',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66ilestream.proto\x12\nfilestream\"&\n\x0b\x46ileRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\x93\x01\n\x08\x46ileData\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12/\n\x04meta\x18\x02 \x03(\x0b\x32!.filestream.FileData.FileMetadata\x12\n\n\x02id\x18\x03 \x01(\t\x1a;\n\x0c\x46ileMetadata\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hunkid\x18\x03 \x01(\x05\"\'\n\x0c\x46ileResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2\xa3\x01\n\x11\x46ileStreamService\x12G\n\x11\x46ileStreamRequest\x12\x14.filestream.FileData\x1a\x18.filestream.FileResponse(\x01\x30\x01\x12\x45\n\x12\x46ileStreamResponse\x12\x17.filestream.FileRequest\x1a\x14.filestream.FileData0\x01\x42\r\xaa\x02\nFileStreamb\x06proto3'
)




_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='filestream.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='filestream.FileRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='filestream.FileRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=70,
)


_FILEDATA_FILEMETADATA = _descriptor.Descriptor(
  name='FileMetadata',
  full_name='filestream.FileData.FileMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='filestream.FileData.FileMetadata.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='filestream.FileData.FileMetadata.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunkid', full_name='filestream.FileData.FileMetadata.chunkid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=220,
)

_FILEDATA = _descriptor.Descriptor(
  name='FileData',
  full_name='filestream.FileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='filestream.FileData.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='filestream.FileData.meta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='filestream.FileData.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FILEDATA_FILEMETADATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=220,
)


_FILERESPONSE = _descriptor.Descriptor(
  name='FileResponse',
  full_name='filestream.FileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='filestream.FileResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='filestream.FileResponse.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=261,
)

_FILEDATA_FILEMETADATA.containing_type = _FILEDATA
_FILEDATA.fields_by_name['meta'].message_type = _FILEDATA_FILEMETADATA
DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
DESCRIPTOR.message_types_by_name['FileData'] = _FILEDATA
DESCRIPTOR.message_types_by_name['FileResponse'] = _FILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'filestream_pb2'
  # @@protoc_insertion_point(class_scope:filestream.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)

FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), {

  'FileMetadata' : _reflection.GeneratedProtocolMessageType('FileMetadata', (_message.Message,), {
    'DESCRIPTOR' : _FILEDATA_FILEMETADATA,
    '__module__' : 'filestream_pb2'
    # @@protoc_insertion_point(class_scope:filestream.FileData.FileMetadata)
    })
  ,
  'DESCRIPTOR' : _FILEDATA,
  '__module__' : 'filestream_pb2'
  # @@protoc_insertion_point(class_scope:filestream.FileData)
  })
_sym_db.RegisterMessage(FileData)
_sym_db.RegisterMessage(FileData.FileMetadata)

FileResponse = _reflection.GeneratedProtocolMessageType('FileResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILERESPONSE,
  '__module__' : 'filestream_pb2'
  # @@protoc_insertion_point(class_scope:filestream.FileResponse)
  })
_sym_db.RegisterMessage(FileResponse)


DESCRIPTOR._options = None

_FILESTREAMSERVICE = _descriptor.ServiceDescriptor(
  name='FileStreamService',
  full_name='filestream.FileStreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=264,
  serialized_end=427,
  methods=[
  _descriptor.MethodDescriptor(
    name='FileStreamRequest',
    full_name='filestream.FileStreamService.FileStreamRequest',
    index=0,
    containing_service=None,
    input_type=_FILEDATA,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FileStreamResponse',
    full_name='filestream.FileStreamService.FileStreamResponse',
    index=1,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESTREAMSERVICE)

DESCRIPTOR.services_by_name['FileStreamService'] = _FILESTREAMSERVICE

# @@protoc_insertion_point(module_scope)
