# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.filestream_pb2 as filestream__pb2


class FileStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileStreamRequest = channel.stream_stream(
                '/filestream.FileStreamService/FileStreamRequest',
                request_serializer=filestream__pb2.FileData.SerializeToString,
                response_deserializer=filestream__pb2.FileResponse.FromString,
                )
        self.FileStreamResponse = channel.unary_stream(
                '/filestream.FileStreamService/FileStreamResponse',
                request_serializer=filestream__pb2.FileRequest.SerializeToString,
                response_deserializer=filestream__pb2.FileData.FromString,
                )


class FileStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FileStreamRequest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileStreamResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileStreamRequest': grpc.stream_stream_rpc_method_handler(
                    servicer.FileStreamRequest,
                    request_deserializer=filestream__pb2.FileData.FromString,
                    response_serializer=filestream__pb2.FileResponse.SerializeToString,
            ),
            'FileStreamResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.FileStreamResponse,
                    request_deserializer=filestream__pb2.FileRequest.FromString,
                    response_serializer=filestream__pb2.FileData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filestream.FileStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FileStreamRequest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/filestream.FileStreamService/FileStreamRequest',
            filestream__pb2.FileData.SerializeToString,
            filestream__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileStreamResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/filestream.FileStreamService/FileStreamResponse',
            filestream__pb2.FileRequest.SerializeToString,
            filestream__pb2.FileData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
